import { createContext, useContext, useMemo, useState } from "react";

export const languages = [
  { code: "en", label: "English", short: "EN" },
  { code: "pt-PT", label: "Português (Portugal)", short: "PT" },
  { code: "pt-BR", label: "Português (Brasil)", short: "BR" },
  { code: "es", label: "Español", short: "ES" },
  { code: "fr", label: "Français", short: "FR" },
  { code: "zh-CN", label: "简体中文", short: "中" },
];

const translations = {
  en: {
    "nav.overview": "Overview",
    "nav.athletes": "Athletes",
    "nav.competitions": "Competitions",
    "nav.staff": "Team staff",
    "nav.sponsors": "Sponsors",
    "nav.results": "Results",
    "nav.disciplines": "Disciplines",
    "nav.roles": "Staff roles",
    "nav.addresses": "Addresses",
    "nav.settings": "Settings",
    "nav.teamManagement": "TEAM MANAGEMENT",
    "nav.account": "ACCOUNT",
    "nav.logout": "Sign out",
    "nav.team": "My team",
    "common.loading": "Loading data...",
    "common.add": "Add",
    "common.edit": "Edit",
    "common.delete": "Delete",
    "common.save": "Save changes",
    "common.cancel": "Cancel",
    "common.list": "List",
    "common.calendar": "Calendar",
    "common.records": "records",
    "common.noRecords": "There are no records to show.",
    "common.backend": "Latest data directly from the API",
    "common.select": "Select an option",
    "common.noAddress": "No address",
    "common.createAddress": "Write a new address",
    "common.newAddress": "New address",
    "login.eyebrow": "CYCLING TEAM MANAGEMENT",
    "login.title": "More time<br/>to <em>ride.</em>",
    "login.description": "Organise people, races and results in one place.",
    "login.welcome": "WELCOME BACK",
    "login.heading": "Sign in to your team",
    "login.subheading": "Use your manager credentials to continue.",
    "login.email": "Professional email",
    "login.password": "Password",
    "login.submit": "Sign in",
    "login.validating": "Checking...",
    "login.noAccount": "Don't have an account?",
    "login.register": "Create one",
    "login.footer": "Built for teams that go further.",
    "register.welcome": "GET STARTED",
    "register.heading": "Create your team account",
    "register.subheading": "Set up your manager profile and team workspace.",
    "register.managerName": "Your name",
    "register.teamName": "Team name",
    "register.submit": "Create account",
    "register.creating": "Creating...",
    "register.hasAccount": "Already have an account?",
    "register.signIn": "Sign in",
    "register.error": "Could not create your account.",
    "dashboard.eyebrow": "OVERVIEW",
    "dashboard.greeting": "Good morning, {name} 👋",
    "dashboard.description": "Here is what is happening with your team.",
    "dashboard.manage": "Manage athletes",
    "dashboard.athletes": "Athletes",
    "dashboard.competitions": "Upcoming competitions",
    "dashboard.results": "Results",
    "dashboard.sponsors": "Sponsors",
    "dashboard.viewInfo": "View information →",
    "dashboard.roster": "ROSTER",
    "dashboard.rosterDescription": "Your active team roster",
    "dashboard.teamAthletes": "Team athletes",
    "dashboard.viewAll": "View all →",
    "dashboard.calendar": "CALENDAR",
    "dashboard.nextCompetitions": "Upcoming competitions",
    "dashboard.upcomingDescription": "Only races still ahead",
    "dashboard.noUpcoming": "No upcoming competitions scheduled.",
    "dashboard.locationUnknown": "Location to be confirmed",
    "settings.eyebrow": "ACCOUNT",
    "settings.title": "Settings",
    "settings.description": "Update your team and manager information.",
    "settings.team": "Team profile",
    "settings.manager": "Manager profile",
    "settings.name": "Name",
    "settings.acronym": "Acronym",
    "settings.phone": "Phone",
    "settings.foundedYear": "Founded year",
    "settings.license": "License",
    "settings.location": "Location",
    "settings.descriptionField": "Description",
    "settings.birthDay": "Date of birth",
    "settings.email": "Email",
    "settings.newPassword": "New password",
    "settings.passwordHint": "Leave empty to keep current password",
    "settings.address": "Address",
    "settings.persisted": "Changes are persisted in the backend.",
    "settings.saved": "Changes saved and persisted.",
    "resource.management": "MANAGEMENT",
    "resource.description": "Real team data, synced with the backend.",
    "resource.add": "Add {item}",
    "resource.saved": "Latest data directly from the API",
    "resource.deleteConfirm": "Delete this {item}?",
    "resource.backendError": "Backend error: {message}{status}",
    "resource.save": "Save {item}",
    "resource.create": "Add {item}",
    "resource.athlete": "athlete",
    "resource.competition": "competition",
    "resource.member": "member",
    "resource.sponsor": "sponsor",
    "resource.discipline": "discipline",
    "resource.role": "role",
    "resource.address": "address",
    "resource.result": "result",
    "fields.fullName": "Full name",
    "fields.dateOfBirth": "Date of birth",
    "fields.email": "Email",
    "fields.password": "Password",
    "fields.phone": "Phone",
    "fields.license": "License",
    "fields.nationality": "Nationality",
    "fields.address": "Address",
    "fields.role": "Role",
    "fields.sponsorName": "Name",
    "fields.website": "Website",
    "fields.type": "Type",
    "fields.activeContract": "Active contract",
    "fields.contractStart": "Contract start",
    "fields.contractEnd": "Contract end",
    "fields.description": "Description",
    "fields.street": "Street",
    "fields.city": "City",
    "fields.district": "District",
    "fields.postalCode": "Postal code",
    "fields.country": "Country",
    "fields.athlete": "Athlete",
    "fields.competition": "Competition",
    "fields.position": "Position",
    "fields.finishTime": "Finish time",
    "fields.points": "Points",
    "fields.dnf": "Did not finish (DNF)",
    "fields.discipline": "Discipline",
    "calendar.eyebrow": "PLANNING",
    "calendar.title": "Competition calendar",
    "calendar.description": "A monthly view of your registered races.",
    "calendar.previous": "Previous month",
    "calendar.next": "Next month",
    "calendar.today": "Today",
    "calendar.selectedDay": "SELECTED DAY",
    "calendar.noEvents": "No competitions scheduled for this day.",
    "calendar.filterLabel": "Show competitions",
    "calendar.filterUpcoming": "Upcoming competitions",
    "calendar.filterAll": "All competitions",
    "calendar.filterPast": "Past competitions",
    "footer.madeBy": "Made by",
    "footer.tagline": "The calm, focused workspace for teams that go further.",
    "footer.source": "Source code",
    "footer.credits": "Credits",
    "footer.license": "Built with React · MIT licensed",
    "home.platform": "Platform",
    "home.features": "Features",
    "home.about": "About",
    "home.signIn": "Sign in",
    "home.getStarted": "Get started",
    "home.eyebrow": "THE OPERATING SYSTEM FOR CYCLING TEAMS",
    "home.title": "Ride together.",
    "home.titleAccent": "Perform further.",
    "home.description":
      "TeamSync brings your riders, staff, competitions and results into one beautifully clear workspace — so your team can focus on the road ahead.",
    "home.cta": "Enter your workspace",
    "home.explore": "Explore the platform",
    "home.proof": "Built for ambitious teams and their next finish line.",
    "home.liveOverview": "LIVE TEAM OVERVIEW",
    "home.teamPerformance": "Team performance",
    "home.riders": "riders",
    "home.races": "races",
    "home.readiness": "ready",
    "home.growth": "this season",
    "home.nextRace": "Next competition",
    "home.why": "ONE CLEAR VIEW",
    "home.featuresTitle": "Everything your team needs to move as one.",
    "home.featuresDescription":
      "From the first training ride to the final result, TeamSync keeps every detail connected and every decision in reach.",
    "home.featureOneTitle": "Your roster, organised",
    "home.featureOneDescription":
      "Keep athlete profiles, staff, roles and contact details accurate, accessible and ready when you need them.",
    "home.featureTwoTitle": "Every race in view",
    "home.featureTwoDescription":
      "Plan competitions, follow results and understand your season with a focused view of what comes next.",
    "home.featureThreeTitle": "Built around your team",
    "home.featureThreeDescription":
      "A flexible workspace that grows with your organisation, backed by your own secure TeamSync data.",
    "home.readyEyebrow": "THE NEXT RIDE STARTS HERE",
    "home.readyTitle": "Make every part of your team work better together.",
    "home.enterWorkspace": "Open TeamSync",
  },
  "pt-PT": {
    "nav.overview": "Visão geral",
    "nav.athletes": "Atletas",
    "nav.competitions": "Competições",
    "nav.staff": "Equipa técnica",
    "nav.sponsors": "Patrocinadores",
    "nav.results": "Resultados",
    "nav.disciplines": "Disciplinas",
    "nav.roles": "Funções de staff",
    "nav.addresses": "Moradas",
    "nav.settings": "Definições",
    "nav.teamManagement": "GESTÃO DA EQUIPA",
    "nav.account": "CONTA",
    "nav.logout": "Terminar sessão",
    "nav.team": "A minha equipa",
    "common.loading": "A carregar dados...",
    "common.add": "Adicionar",
    "common.edit": "Editar",
    "common.delete": "Eliminar",
    "common.save": "Guardar alterações",
    "common.cancel": "Cancelar",
    "common.list": "Lista",
    "common.calendar": "Calendário",
    "common.records": "registos",
    "common.noRecords": "Ainda não existem registos para mostrar.",
    "common.backend": "Última leitura diretamente da API",
    "common.select": "Seleciona uma opção",
    "common.noAddress": "Sem morada",
    "login.eyebrow": "GESTÃO DE EQUIPAS DE CICLISMO",
    "login.title": "Mais tempo<br/>para <em>pedalar.</em>",
    "login.description": "Organiza pessoas, provas e resultados num só lugar.",
    "login.welcome": "BEM-VINDO DE VOLTA",
    "login.heading": "Entra na tua equipa",
    "login.subheading": "Usa as credenciais do teu manager para continuar.",
    "login.email": "Email profissional",
    "login.password": "Password",
    "login.submit": "Iniciar sessão",
    "login.validating": "A validar...",
    "login.footer": "Feito para equipas que vão mais longe.",
    "dashboard.eyebrow": "VISÃO GERAL",
    "dashboard.greeting": "Bom dia, {name} 👋",
    "dashboard.description": "Aqui está o que se passa na tua equipa.",
    "dashboard.manage": "Gerir atletas",
    "dashboard.athletes": "Atletas",
    "dashboard.competitions": "Próximas competições",
    "dashboard.results": "Resultados",
    "dashboard.sponsors": "Patrocinadores",
    "dashboard.viewInfo": "Ver informação →",
    "dashboard.roster": "PLANTEL",
    "dashboard.rosterDescription": "O plantel atual da equipa",
    "dashboard.teamAthletes": "Atletas da equipa",
    "dashboard.viewAll": "Ver tudo →",
    "dashboard.calendar": "CALENDÁRIO",
    "dashboard.nextCompetitions": "Próximas provas",
    "dashboard.upcomingDescription": "Apenas provas futuras",
    "dashboard.noUpcoming": "Não existem próximas provas marcadas.",
    "dashboard.locationUnknown": "Local por confirmar",
    "settings.eyebrow": "CONTA",
    "settings.title": "Definições",
    "settings.description":
      "Atualiza toda a informação da equipa e do manager.",
    "settings.team": "Perfil da equipa",
    "settings.manager": "Perfil do manager",
    "settings.name": "Nome",
    "settings.acronym": "Sigla",
    "settings.phone": "Telefone",
    "settings.foundedYear": "Ano de fundação",
    "settings.license": "Licença",
    "settings.location": "Localização",
    "settings.descriptionField": "Descrição",
    "settings.birthDay": "Data de nascimento",
    "settings.email": "Email",
    "settings.newPassword": "Nova password",
    "settings.passwordHint": "Deixa vazio para manter",
    "settings.address": "Morada",
    "settings.persisted": "As alterações são persistidas no backend.",
    "settings.saved": "Alterações guardadas e persistidas.",
    "resource.management": "GESTÃO",
    "resource.description":
      "Dados reais da tua equipa, sincronizados com o backend.",
    "resource.add": "Adicionar {item}",
    "resource.saved": "Última leitura diretamente da API",
    "resource.deleteConfirm": "Eliminar este {item}?",
    "resource.backendError": "Erro do backend: {message}{status}",
    "resource.save": "Guardar {item}",
    "resource.create": "Adicionar {item}",
    "resource.athlete": "atleta",
    "resource.competition": "competição",
    "resource.member": "membro",
    "resource.sponsor": "patrocinador",
    "resource.discipline": "disciplina",
    "resource.role": "função",
    "resource.address": "morada",
    "resource.result": "resultado",
    "fields.fullName": "Nome completo",
    "fields.dateOfBirth": "Data de nascimento",
    "fields.email": "Email",
    "fields.password": "Password",
    "fields.phone": "Telefone",
    "fields.license": "Licença",
    "fields.nationality": "Nacionalidade",
    "fields.address": "Morada",
    "fields.role": "Função",
    "fields.sponsorName": "Nome",
    "fields.website": "Website",
    "fields.type": "Tipo",
    "fields.activeContract": "Contrato ativo",
    "fields.contractStart": "Início do contrato",
    "fields.contractEnd": "Fim do contrato",
    "fields.description": "Descrição",
    "fields.street": "Rua",
    "fields.city": "Cidade",
    "fields.district": "Distrito",
    "fields.postalCode": "Código postal",
    "fields.country": "País",
    "fields.athlete": "Atleta",
    "fields.competition": "Competição",
    "fields.position": "Posição",
    "fields.finishTime": "Tempo final",
    "fields.points": "Pontos",
    "fields.dnf": "Não terminou (DNF)",
    "fields.discipline": "Disciplina",
    "calendar.eyebrow": "PLANEAMENTO",
    "calendar.title": "Calendário de competições",
    "calendar.description": "Uma visão mensal das provas registadas.",
    "calendar.previous": "Mês anterior",
    "calendar.next": "Próximo mês",
    "calendar.today": "Hoje",
    "calendar.selectedDay": "DIA SELECIONADO",
    "calendar.noEvents": "Não existem competições marcadas para este dia.",
    "calendar.filterLabel": "Mostrar competições",
    "calendar.filterUpcoming": "Próximas competições",
    "calendar.filterAll": "Todas as competições",
    "calendar.filterPast": "Competições passadas",
    "footer.madeBy": "Made by",
  },
};

const homeTranslations = {
  "pt-PT": {
    "home.platform": "Plataforma",
    "home.features": "Funcionalidades",
    "home.about": "Sobre",
    "home.signIn": "Entrar",
    "home.getStarted": "Começar",
    "home.eyebrow": "O SISTEMA OPERATIVO PARA EQUIPAS DE CICLISMO",
    "home.title": "Pedala em conjunto.",
    "home.titleAccent": "Vai mais longe.",
    "home.description":
      "O TeamSync reúne atletas, staff, competições e resultados num espaço claro e elegante — para a tua equipa se focar no caminho.",
    "home.cta": "Entrar no workspace",
    "home.explore": "Explorar a plataforma",
    "home.proof": "Criado para equipas ambiciosas e a próxima meta.",
    "home.liveOverview": "VISÃO GERAL EM DIRETO",
    "home.teamPerformance": "Performance da equipa",
    "home.riders": "atletas",
    "home.races": "provas",
    "home.readiness": "prontos",
    "home.growth": "esta época",
    "home.nextRace": "Próxima competição",
    "home.why": "UMA VISÃO CLARA",
    "home.featuresTitle":
      "Tudo o que a tua equipa precisa para avançar em conjunto.",
    "home.featuresDescription":
      "Do primeiro treino ao resultado final, o TeamSync mantém todos os detalhes ligados e cada decisão acessível.",
    "home.featureOneTitle": "Plantel organizado",
    "home.featureOneDescription":
      "Mantém perfis de atletas, staff, funções e contactos corretos e acessíveis.",
    "home.featureTwoTitle": "Todas as provas à vista",
    "home.featureTwoDescription":
      "Planeia competições, acompanha resultados e entende a tua época.",
    "home.featureThreeTitle": "Feito para a tua equipa",
    "home.featureThreeDescription":
      "Um workspace flexível que cresce com a tua organização.",
    "home.readyEyebrow": "A PRÓXIMA VOLTA COMEÇA AQUI",
    "home.readyTitle":
      "Faz com que cada parte da tua equipa trabalhe melhor em conjunto.",
    "home.enterWorkspace": "Abrir TeamSync",
  },
  "pt-BR": {
    "home.platform": "Plataforma",
    "home.features": "Recursos",
    "home.about": "Sobre",
    "home.signIn": "Entrar",
    "home.getStarted": "Começar",
    "home.eyebrow": "O SISTEMA OPERACIONAL PARA EQUIPES DE CICLISMO",
    "home.title": "Pedale junto.",
    "home.titleAccent": "Vá mais longe.",
    "home.description":
      "O TeamSync reúne ciclistas, equipe, competições e resultados em um espaço claro e elegante.",
    "home.cta": "Entrar no workspace",
    "home.explore": "Explorar a plataforma",
    "home.proof":
      "Feito para equipes ambiciosas e sua próxima linha de chegada.",
    "home.liveOverview": "VISÃO GERAL AO VIVO",
    "home.teamPerformance": "Desempenho da equipe",
    "home.riders": "ciclistas",
    "home.races": "provas",
    "home.readiness": "prontos",
    "home.growth": "nesta temporada",
    "home.nextRace": "Próxima competição",
    "home.why": "UMA VISÃO CLARA",
    "home.featuresTitle": "Tudo o que sua equipe precisa para avançar junta.",
    "home.featuresDescription":
      "Do primeiro treino ao resultado final, o TeamSync mantém tudo conectado.",
    "home.featureOneTitle": "Elenco organizado",
    "home.featureOneDescription":
      "Mantenha perfis, funções e contatos sempre acessíveis.",
    "home.featureTwoTitle": "Cada prova em foco",
    "home.featureTwoDescription":
      "Planeje competições e acompanhe seus resultados.",
    "home.featureThreeTitle": "Feito para sua equipe",
    "home.featureThreeDescription":
      "Um workspace flexível que cresce com sua organização.",
    "home.readyEyebrow": "A PRÓXIMA VOLTA COMEÇA AQUI",
    "home.readyTitle": "Faça sua equipe trabalhar melhor em conjunto.",
    "home.enterWorkspace": "Abrir TeamSync",
  },
  es: {
    "home.platform": "Plataforma",
    "home.features": "Funciones",
    "home.about": "Sobre nosotros",
    "home.signIn": "Iniciar sesión",
    "home.getStarted": "Empezar",
    "home.eyebrow": "EL SISTEMA OPERATIVO PARA EQUIPOS DE CICLISMO",
    "home.title": "Pedalead juntos.",
    "home.titleAccent": "Llegad más lejos.",
    "home.description":
      "TeamSync reúne ciclistas, equipo, competiciones y resultados en un espacio claro y elegante.",
    "home.cta": "Entrar al workspace",
    "home.explore": "Explorar la plataforma",
    "home.proof": "Creado para equipos ambiciosos y su próxima meta.",
    "home.liveOverview": "VISIÓN DEL EQUIPO EN DIRECTO",
    "home.teamPerformance": "Rendimiento del equipo",
    "home.riders": "ciclistas",
    "home.races": "carreras",
    "home.readiness": "listos",
    "home.growth": "esta temporada",
    "home.nextRace": "Próxima competición",
    "home.why": "UNA VISIÓN CLARA",
    "home.featuresTitle": "Todo lo que tu equipo necesita para avanzar unido.",
    "home.featuresDescription":
      "Del primer entrenamiento al resultado final, TeamSync conecta cada detalle.",
    "home.featureOneTitle": "Plantilla organizada",
    "home.featureOneDescription":
      "Perfiles, funciones y contactos siempre accesibles.",
    "home.featureTwoTitle": "Cada carrera a la vista",
    "home.featureTwoDescription":
      "Planifica competiciones y sigue los resultados.",
    "home.featureThreeTitle": "Diseñado para tu equipo",
    "home.featureThreeDescription": "Un workspace flexible que crece contigo.",
    "home.readyEyebrow": "LA PRÓXIMA VUELTA EMPIEZA AQUÍ",
    "home.readyTitle": "Haz que cada parte de tu equipo trabaje mejor junta.",
    "home.enterWorkspace": "Abrir TeamSync",
  },
  fr: {
    "home.platform": "Plateforme",
    "home.features": "Fonctionnalités",
    "home.about": "À propos",
    "home.signIn": "Se connecter",
    "home.getStarted": "Commencer",
    "home.eyebrow": "LE SYSTÈME DES ÉQUIPES CYCLISTES",
    "home.title": "Roulez ensemble.",
    "home.titleAccent": "Allez plus loin.",
    "home.description":
      "TeamSync rassemble coureurs, équipe, compétitions et résultats dans un espace clair et élégant.",
    "home.cta": "Accéder à l’espace",
    "home.explore": "Découvrir la plateforme",
    "home.proof":
      "Conçu pour les équipes ambitieuses et leur prochaine ligne d’arrivée.",
    "home.liveOverview": "VUE DE L’ÉQUIPE EN DIRECT",
    "home.teamPerformance": "Performance de l’équipe",
    "home.riders": "coureurs",
    "home.races": "courses",
    "home.readiness": "prêts",
    "home.growth": "cette saison",
    "home.nextRace": "Prochaine compétition",
    "home.why": "UNE VUE UNIQUE",
    "home.featuresTitle":
      "Tout ce dont votre équipe a besoin pour avancer ensemble.",
    "home.featuresDescription":
      "Du premier entraînement au résultat final, TeamSync relie chaque détail.",
    "home.featureOneTitle": "Effectif organisé",
    "home.featureOneDescription":
      "Profils, rôles et contacts toujours accessibles.",
    "home.featureTwoTitle": "Chaque course en vue",
    "home.featureTwoDescription":
      "Planifiez les compétitions et suivez les résultats.",
    "home.featureThreeTitle": "Pensé pour votre équipe",
    "home.featureThreeDescription": "Un espace flexible qui évolue avec vous.",
    "home.readyEyebrow": "LA PROCHAINE SORTIE COMMENCE ICI",
    "home.readyTitle": "Faites mieux travailler chaque partie de votre équipe.",
    "home.enterWorkspace": "Ouvrir TeamSync",
  },
  "zh-CN": {
    "home.platform": "平台",
    "home.features": "功能",
    "home.about": "关于",
    "home.signIn": "登录",
    "home.getStarted": "开始使用",
    "home.eyebrow": "自行车队的运营系统",
    "home.title": "一起骑行。",
    "home.titleAccent": "走得更远。",
    "home.description":
      "TeamSync 将车手、工作人员、赛事和成绩集中在一个清晰优雅的空间中。",
    "home.cta": "进入工作区",
    "home.explore": "探索平台",
    "home.proof": "为有抱负的车队和下一条终点线而打造。",
    "home.liveOverview": "实时车队概览",
    "home.teamPerformance": "车队表现",
    "home.riders": "车手",
    "home.races": "赛事",
    "home.readiness": "准备就绪",
    "home.growth": "本赛季",
    "home.nextRace": "下一场赛事",
    "home.why": "清晰视图",
    "home.featuresTitle": "车队共同前进所需的一切。",
    "home.featuresDescription":
      "从第一次训练到最终成绩，TeamSync 让每个细节保持连接。",
    "home.featureOneTitle": "有序管理阵容",
    "home.featureOneDescription": "随时访问车手、职员、角色和联系方式。",
    "home.featureTwoTitle": "掌握每场比赛",
    "home.featureTwoDescription": "规划赛事并跟踪赛季成绩。",
    "home.featureThreeTitle": "围绕车队打造",
    "home.featureThreeDescription": "随着组织成长而扩展的灵活工作区。",
    "home.readyEyebrow": "下一次骑行从这里开始",
    "home.readyTitle": "让车队的每个部分更好地协同工作。",
    "home.enterWorkspace": "打开 TeamSync",
  },
};

translations["pt-BR"] = {
  ...translations["pt-PT"],
  "nav.team": "Minha equipe",
  "nav.staff": "Equipe técnica",
  "nav.logout": "Sair",
  "common.loading": "Carregando dados...",
  "common.add": "Adicionar",
  "common.edit": "Editar",
  "common.delete": "Excluir",
  "common.save": "Salvar alterações",
  "common.cancel": "Cancelar",
  "common.select": "Selecione uma opção",
  "common.noRecords": "Ainda não existem registros para mostrar.",
  "dashboard.greeting": "Bom dia, {name} 👋",
  "settings.phone": "Telefone",
  "settings.location": "Localização",
};
translations.es = {
  ...translations.en,
  "nav.overview": "Resumen",
  "nav.athletes": "Ciclistas",
  "nav.competitions": "Competiciones",
  "nav.staff": "Equipo técnico",
  "nav.sponsors": "Patrocinadores",
  "nav.results": "Resultados",
  "nav.settings": "Configuración",
  "nav.logout": "Cerrar sesión",
  "nav.teamManagement": "GESTIÓN DEL EQUIPO",
  "nav.account": "CUENTA",
  "common.loading": "Cargando datos...",
  "common.add": "Añadir",
  "common.edit": "Editar",
  "common.delete": "Eliminar",
  "common.save": "Guardar cambios",
  "common.select": "Selecciona una opción",
  "login.heading": "Entra en tu equipo",
  "login.subheading": "Usa las credenciales de tu manager.",
  "login.submit": "Iniciar sesión",
  "dashboard.greeting": "Buenos días, {name} 👋",
  "dashboard.description": "Esto es lo que ocurre en tu equipo.",
  "settings.title": "Configuración",
  "footer.madeBy": "Creado por",
};
translations.fr = {
  ...translations.en,
  "nav.overview": "Vue générale",
  "nav.athletes": "Coureurs",
  "nav.competitions": "Compétitions",
  "nav.staff": "Équipe technique",
  "nav.sponsors": "Sponsors",
  "nav.results": "Résultats",
  "nav.settings": "Paramètres",
  "nav.logout": "Se déconnecter",
  "nav.teamManagement": "GESTION DE L’ÉQUIPE",
  "nav.account": "COMPTE",
  "common.loading": "Chargement...",
  "common.add": "Ajouter",
  "common.edit": "Modifier",
  "common.delete": "Supprimer",
  "common.save": "Enregistrer",
  "common.select": "Sélectionner une option",
  "login.heading": "Accédez à votre équipe",
  "login.submit": "Se connecter",
  "dashboard.greeting": "Bonjour, {name} 👋",
  "settings.title": "Paramètres",
  "footer.madeBy": "Créé par",
};
translations["zh-CN"] = {
  ...translations.en,
  "nav.overview": "概览",
  "nav.athletes": "运动员",
  "nav.competitions": "比赛",
  "nav.staff": "技术团队",
  "nav.sponsors": "赞助商",
  "nav.results": "成绩",
  "nav.settings": "设置",
  "nav.logout": "退出登录",
  "nav.teamManagement": "团队管理",
  "nav.account": "账户",
  "common.loading": "正在加载...",
  "common.add": "添加",
  "common.edit": "编辑",
  "common.delete": "删除",
  "common.save": "保存更改",
  "common.select": "请选择",
  "login.heading": "登录你的团队",
  "login.submit": "登录",
  "dashboard.greeting": "早上好，{name} 👋",
  "settings.title": "设置",
  "footer.madeBy": "制作人",
};

const LanguageContext = createContext(null);
const commonTranslations = {
  en: {
    "common.createAddress": "Write a new address",
    "common.newAddress": "New address",
    "common.view": "View",
    "competitionAssociation.eyebrow": "TEAM SELECTION",
    "competitionAssociation.title": "Athletes in this competition",
    "competitionAssociation.selected": "selected",
    "competitionAssociation.competition": "Competition",
    "competitionAssociation.choose":
      "Choose a competition to manage its athletes.",
    "competitionDetails.eyebrow": "COMPETITION DETAILS",
    "results.eyebrow": "PERFORMANCE",
    "results.description":
      "Review results by competition or across the whole team.",
    "results.filter": "Filter by competition",
    "results.allCompetitions": "All competitions",
    "results.teamOverview": "Team results overview",
    "results.competitionResults": "Competition results",
    "results.athletes": "Athletes",
    "results.points": "Team points",
    "results.finished": "Finished",
    "results.competitions": "Competitions",
  },
  "pt-PT": {
    "common.createAddress": "Escrever uma nova morada",
    "common.newAddress": "Nova morada",
    "competitionAssociation.eyebrow": "SELEÇÃO DA EQUIPA",
    "competitionAssociation.title": "Atletas nesta competição",
    "competitionAssociation.selected": "selecionados",
    "competitionAssociation.competition": "Competição",
    "competitionAssociation.choose":
      "Escolhe uma competição para gerir os seus atletas.",
    "competitionDetails.eyebrow": "DETALHES DA COMPETIÇÃO",
    "results.eyebrow": "PERFORMANCE",
    "results.description":
      "Consulta os resultados por competição ou de toda a equipa.",
    "results.filter": "Filtrar por competição",
    "results.allCompetitions": "Todas as competições",
    "results.teamOverview": "Resumo dos resultados da equipa",
    "results.competitionResults": "Resultados da competição",
    "results.athletes": "Atletas",
    "results.points": "Pontos da equipa",
    "results.finished": "Concluíram",
    "results.competitions": "Competições",
  },
  "pt-BR": {
    "common.createAddress": "Escrever um novo endereço",
    "common.newAddress": "Novo endereço",
    "competitionAssociation.eyebrow": "SELEÇÃO DA EQUIPE",
    "competitionAssociation.title": "Ciclistas nesta competição",
    "competitionAssociation.selected": "selecionados",
    "competitionAssociation.competition": "Competição",
    "competitionAssociation.choose":
      "Escolha uma competição para gerenciar seus ciclistas.",
    "competitionDetails.eyebrow": "DETALHES DA COMPETIÇÃO",
    "results.eyebrow": "DESEMPENHO",
    "results.description":
      "Consulte os resultados por competição ou de toda a equipe.",
    "results.filter": "Filtrar por competição",
    "results.allCompetitions": "Todas as competições",
    "results.teamOverview": "Resumo dos resultados da equipe",
    "results.competitionResults": "Resultados da competição",
    "results.athletes": "Ciclistas",
    "results.points": "Pontos da equipe",
    "results.finished": "Finalizados",
    "results.competitions": "Competições",
  },
  es: {
    "common.createAddress": "Escribir una nueva dirección",
    "common.newAddress": "Nueva dirección",
    "competitionAssociation.eyebrow": "SELECCIÓN DEL EQUIPO",
    "competitionAssociation.title": "Ciclistas en esta competición",
    "competitionAssociation.selected": "seleccionados",
    "competitionAssociation.competition": "Competición",
    "competitionAssociation.choose":
      "Elige una competición para gestionar sus ciclistas.",
    "competitionDetails.eyebrow": "DETALLES DE LA COMPETICIÓN",
    "results.eyebrow": "RENDIMIENTO",
    "results.description":
      "Consulta resultados por competición o de todo el equipo.",
    "results.filter": "Filtrar por competición",
    "results.allCompetitions": "Todas las competiciones",
    "results.teamOverview": "Resumen de resultados del equipo",
    "results.competitionResults": "Resultados de la competición",
    "results.athletes": "Ciclistas",
    "results.points": "Puntos del equipo",
    "results.finished": "Finalizados",
    "results.competitions": "Competiciones",
  },
  fr: {
    "common.createAddress": "Écrire une nouvelle adresse",
    "common.newAddress": "Nouvelle adresse",
    "competitionAssociation.eyebrow": "SÉLECTION DE L’ÉQUIPE",
    "competitionAssociation.title": "Coureurs dans cette compétition",
    "competitionAssociation.selected": "sélectionnés",
    "competitionAssociation.competition": "Compétition",
    "competitionAssociation.choose":
      "Choisissez une compétition pour gérer ses coureurs.",
    "competitionDetails.eyebrow": "DÉTAILS DE LA COMPÉTITION",
    "results.eyebrow": "PERFORMANCE",
    "results.description":
      "Consultez les résultats par compétition ou pour toute l’équipe.",
    "results.filter": "Filtrer par compétition",
    "results.allCompetitions": "Toutes les compétitions",
    "results.teamOverview": "Résumé des résultats de l’équipe",
    "results.competitionResults": "Résultats de la compétition",
    "results.athletes": "Coureurs",
    "results.points": "Points de l’équipe",
    "results.finished": "Terminés",
    "results.competitions": "Compétitions",
  },
  "zh-CN": {
    "common.createAddress": "填写新地址",
    "common.newAddress": "新地址",
    "competitionAssociation.eyebrow": "车队选择",
    "competitionAssociation.title": "参加此赛事的车手",
    "competitionAssociation.selected": "已选择",
    "competitionAssociation.competition": "赛事",
    "competitionAssociation.choose": "选择一场赛事来管理车手。",
    "competitionDetails.eyebrow": "赛事详情",
    "results.eyebrow": "表现",
    "results.description": "按赛事查看结果或查看整个车队的结果。",
    "results.filter": "按赛事筛选",
    "results.allCompetitions": "所有赛事",
    "results.teamOverview": "车队结果概览",
    "results.competitionResults": "赛事结果",
    "results.athletes": "车手",
    "results.points": "车队积分",
    "results.finished": "已完成",
    "results.competitions": "赛事",
  },
};

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState(
    () => localStorage.getItem("teamsync_language") || "en",
  );
  function changeLanguage(next) {
    localStorage.setItem("teamsync_language", next);
    setLanguage(next);
  }
  function t(key, variables = {}) {
    let value =
      commonTranslations[language]?.[key] ||
      homeTranslations[language]?.[key] ||
      translations[language]?.[key] ||
      commonTranslations.en?.[key] ||
      translations.en[key] ||
      key;
    Object.entries(variables).forEach(([name, replacement]) => {
      value = value.replace(`{${name}}`, replacement);
    });
    return value;
  }
  const value = useMemo(
    () => ({ language, changeLanguage, languages, t }),
    [language],
  );
  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
}
export function useLanguage() {
  return useContext(LanguageContext);
}
